### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by Ade179**
### Accessibility 

- Page title added (https://github.com/Ade179/Professional-Portfolio/blob/3ef46a9299ddb08359a6fea094f38cc605dfba7d/index.html#L9)
- image text alternative added (https://github.com/Ade179/Professional-Portfolio/blob/3ef46a9299ddb08359a6fea094f38cc605dfba7d/index.html#L245)
- multimedia (no issue found)
- basic page of HTML structure (no issue found)
- moving content (no issue found)
- Text headings (no issues found)
- colour contrast (21 issues found but changes will affect the basic structure of the page and will cause a huge difference from the Figma template)
- Logo is given hover effect for people with lesser visual strength and can only see more prominent texts
- semantic stages in HTML have been fixed to fit with displayed content

### CODE REVIEW

**Review by awais-amjed — COMMENTED** [review]
Hi @Ade179 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, that has linter issues.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Qoosim — CHANGES_REQUESTED** [review]
# *Status: Required Changes* :recycle: 

Hi @Ade179 and @Outkarm, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors. :heavy_check_mark: 
-  Good Githib Flow. :heavy_check_mark: 
-  Evaluation Performed. :heavy_check_mark: 
-  Good commit messages. :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Good jog on evaluating your website against accessibility best practices. You've done pretty well. However, there are still few things that aren't addressed yet. After checking your live version link on this [site](https://www.aditus.io/button-contrast-checker/ade179-github-io-2022-08-31-at-10-15-22-060?failing). I found out that your site has eight failing elements that you need to address before you can move on to the next project. Kindly check the attached image to see those failed elements and try to implement the necessary changes to make them pass.
- [ ] Kindly check the project [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) to know all the items you are expected to check on your project. and give a proper report format like this **Page titles: `No issue found`** etc.
- [ ] Also, I can see an horizontal scroll bar on your site when I opened your live version link. Kindly look into that too and fix it. Happy coding. :man_technologist:

color-checker

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @Ade179, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - No linter errors. ✔️
 - Good use of Github flow. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] As the previous Code Reviewer mentioned, please use a proper format for your report. If you changed something, [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148). Here is an example of how your report should look like:
>
image
 --------------------------------------------
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ade179** [comment]
### Accessibility 

- Page title added (https://github.com/Ade179/Professional-Portfolio/blob/3ef46a9299ddb08359a6fea094f38cc605dfba7d/index.html#L9)
- image text alternative added (https://github.com/Ade179/Professional-Portfolio/blob/3ef46a9299ddb08359a6fea094f38cc605dfba7d/index.html#L245)
- multimedia (no issue found)
- basic page of HTML structure (no issue found)
- moving content (no issue found)
- Text headings (no issues found)
- colour contrast (21 issues found but changes will affect the basic structure of the page and will cause a huge difference from the Figma template)
- Logo is given hover effect for people with lesser visual strength and can only see more prominent texts
- semantic stages in HTML have been fixed to fit with displayed content

**Pull request merged**
