### PR TITLE
Dynamic modal popups

### PR DESCRIPTION
**Pull request by Ade179**
### pair programming by @Jaymelfah  and @Ade179 

- modal popups were added to both desktop and mobile versions of the project
- live links and live source  links were added to pop-up buttons
- passes linters test
- correct GitHub workflow was implemented

### CODE REVIEW

**Review by BenMukebo — CHANGES_REQUESTED** [review]
Hi @Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. ✔️ 
- GitHub flow was correctly used.  ✔️   
- The [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters is set correctly  ✔️ 
-  When the user clicks the button to check project details, the popup with details about the project appears.✔️   
- When the user clicks the close button, the popup disappears ✔️ 
- You have followed  JavaScript best practices. ✔️ 



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ]  Please, add a meaningful  `Project description`. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. Think of it as the elevator pitch that focuses on what and why without delving into how. 😉 💯 

- [ ] Please update your Readme, currently, some headings are missing such as:

``` ##  Getting Started ```

- [ ] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd project_name`, etc 🙃  Please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.


``` ## Authors ```

- [OPTIONAL] This is a group project. Please let's include all the authors in the README file. This makes the README file professional and descriptive. 👨🏻‍🎨 

## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

- [ ] When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![00Mit](https://user-images.githubusercontent.com/79058364/182822618-fdfb2523-cb23-4060-9f72-75ec8c29e4cd.png)

#### The reason for this is that there is no `MIT.md` file in the root directory of this project. Kindly attach the file. 👍

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by tresorsawasawa — CHANGES_REQUESTED** [review]
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @samuelmoiwa 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

almost-there

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions
- [ ] Please, add a meaningful Project description. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. Think of it as the elevator pitch that focuses on what and why without delving into how. 

- [ ] Kindly make sure you update your Readme, currently, some headings are missing such as:

  - `## Getting Started`
    It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes git clone URL , cd project_name, etc upside_down_face Please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- [ ] `## Authors` **Section:** This is a group project. Please let's include all the authors in the README file. This makes the README file professional and descriptive. 👨🏻‍🎨

 - [ ] I would also recommend adding the Contributing section with the link to the issue page:

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```
- [ ]  When a click the link to the MIT.md file that you added, it raises this **[404 error](https://github.com/Ade179/Professional-Portfolio/blob/main/LICENSE)**. Kindly make sure you fix that to make your README professional. You can get the [MIT.md file from this template](https://github.com/microverseinc/readme-template/blob/master/MIT.md) and edit its path in your `README.md` file to fix the error.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nicupop729 — COMMENTED** [review]
Hello @Ade179 & @Jaymelfah  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the excellent work you have done until now!

I noticed that you are not using loops in your project. Because of this, the JS file is very long and hard to read and follow. You can consider this as an optional requirement.

Also, what both Code Reviewers meant is that you should delete the entire content of the work projects from your HTML file and inject it with the help of JavaScript, using DOM manipulation.
At the moment, you have the skeleton of the projects in your HTML file and you populate them with JavaScript.

The extra thing that you need to do is to create that structure completely using JavaScript.

Your code in the HTML file should look like this:
```
 <article id="move">
        <section class="MyWorks">      
         "insertion of work cards using JavaScript and DOM manipulation"
        </section>
    </article>
```

Please take the time to read the following documentation like [this one](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) or [this one](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML).

After you have done this, please ask for another review in your dashboard.

Keep rocking 🚀!

**Review by Munsa1 — APPROVED** [review]
Hi @Ade179, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
